version: "3"
services:
  sync0:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sync0
    ports:
      - "8080:8080"
    command: ["dart", "sync_server.dart", "0"]
    volumes:
      - /etc/localtime:/etc/localtime:ro # Herda o relógio do host

  sync1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sync1
    ports:
      - "8081:8080"
    command: ["dart", "sync_server.dart", "1"]
    volumes:
      - /etc/localtime:/etc/localtime:ro # Herda o relógio do host


  # sync2:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: sync2
  #   ports:
  #     - "8082:8080"
  #   command: ["dart", "sync_server.dart", "2"]
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro # Herda o relógio do host

  # sync3:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: sync3
  #   ports:
  #     - "8083:8080"
  #   command: ["dart", "sync_server.dart", "3"]
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro # Herda o relógio do host

  # sync4:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: sync4
  #   ports:
  #     - "8084:8080"
  #   command: ["dart", "sync_server.dart", "4"]
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro # Herda o relógio do host
