version: "3"
services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"

  storage0:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storage0
    ports:
      - "8085:8080"
    depends_on:
      - redis
    command: ["dart", "storage_server.dart", "0", "true"]
    volumes:
      - /etc/localtime:/etc/localtime:ro

  storage1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storage1
    ports:
      - "8086:8080"
    depends_on:
      - redis
      - storage0
    command: ["dart", "storage_server.dart", "1", "false"]
    volumes:
      - /etc/localtime:/etc/localtime:ro

  storage2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storage2
    ports:
      - "8087:8080"
    depends_on:
      - redis
      - storage1
    command: ["dart", "storage_server.dart", "2", "false"]
    volumes:
      - /etc/localtime:/etc/localtime:ro

  sync0:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sync0
    ports:
      - "8080:8080"
    command: ["dart", "sync_server.dart", "0"]
    depends_on:
      - storage0
      - storage1
      - storage2
    volumes:
      - /etc/localtime:/etc/localtime:ro # Herda o relógio do host

  sync1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sync1
    ports:
      - "8081:8080"
    command: ["dart", "sync_server.dart", "1"]
    depends_on:
      - storage0
      - storage1
      - storage2
    volumes:
      - /etc/localtime:/etc/localtime:ro # Herda o relógio do host

  sync2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sync2
    ports:
      - "8082:8080"
    command: ["dart", "sync_server.dart", "2"]
    depends_on:
      - storage0
      - storage1
      - storage2
    volumes:
      - /etc/localtime:/etc/localtime:ro # Herda o relógio do host

  sync3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sync3
    ports:
      - "8083:8080"
    command: ["dart", "sync_server.dart", "3"]
    depends_on:
      - storage0
      - storage1
      - storage2
    volumes:
      - /etc/localtime:/etc/localtime:ro # Herda o relógio do host

  sync4:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sync4
    ports:
      - "8084:8080"
    command: ["dart", "sync_server.dart", "4"]
    depends_on:
      - storage0
      - storage1
      - storage2
    volumes:
      - /etc/localtime:/etc/localtime:ro # Herda o relógio do host
