name: tp2_server
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.5.1

dependencies:
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  logging: ^1.2.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
